### ISSUE TITLE
SIM Card bootloop?

### ISSUE THREAD

**Issue by DerekJ123** [bdogg718k/Fixed_or_Broken#1]
Hi, I have a problem where whenever my sim card is in my phone, right when it is recognized, the phone goes into a bootloop....I have attached my logcat in this link: https://drive.google.com/file/d/0BzKUEuxMtLAwMmduRDhsVDNlWnM/view?usp=sharing
Note: Even though this logcat is from the previous build, the new build's logcat looks the exact same and has the exact same problem.

**Comment by bdogg718k** [comment]
Yes I know. I have seen this log MANY TIMES. This seems to be very carrier specific. This build and last has been confirmed working on all 4 major carriers. We (TEAM-M8) are very aware of this issue and will publish a fix as soon as we find one. Who knows...CM might find it first. :-P

**Comment by Awooiel** [comment]
Are there any updates on this in terms of bug fixes? I was dealing with this issue two weeks ago. It forced me to switch back to Marshmallow.
