### ISSUE TITLE
M8 share network hotsopt get error

### ISSUE THREAD

**Issue by tasi788** [bdogg718k/Fixed_or_Broken#3]
I turn on tethering and get error just like below
![15390987_1243212182437915_5494261276714324524_n 1](https://cloud.githubusercontent.com/assets/11913223/21079281/8e7c1ad8-bfc8-11e6-9b2a-aedacfb94cb4.jpg)
I got this msg both wifi and usb

**Comment by mtayyabali** [comment]
I am getting the same error..

**Comment by evgeny-gist** [comment]
+
